version: "3.8"

services:
  # custom image

  database:
        image: mysql
        restart: always
        container_name: 'database'
        ports:
          - 3311:3306
        volumes:
          - ./.docker/mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        expose:
          - "3306"
        environment:
          MYSQL_DATABASE: ${DB_NAME}
          MYSQL_ROOT_PASSWORD: 123456
          MYSQL_USER: diego
          MYSQL_PASSWORD: 123456
        networks:
          - projeto-api-node

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: 'api'
    image: diegojacober/apinode
    working_dir: /var/www/
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - projeto-api-node



networks:
  projeto-api-node:
    driver: bridge